/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.concurrent.ForkJoinPool;

public class App {
    public static void main(String[] args) {
        String url = "https://skillbox.ru/";
        Parser parser = new Parser(url);
        new ForkJoinPool().invoke(new FactorialTask(parser, parser.getUrls(url)));
        FileCreator creator = new FileCreator(parser.getSiteMap(), url);
    }
}
